channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - sphinx==4.0.2
  - sphinx-copybutton==0.4.0
  - python==3.8
  - myst-parser==0.15.1
  - pip==21.2.*
#  - nbsphinx==0.8.1
  - pip:
    - sphinx_rtd_theme==0.5.2
    - sphinx-comments==0.0.3
    - sphinxcontrib-mermaid==0.7.1